---
name: fontconfig
version: 0.1.0
homepage: https://wiki.freedesktop.org/www/Software/fontconfig/
description: XML-based font configuration API for X Windows

_macos: &macos
  install: brew install fontconfig
  check: command -v fc-list
  dependencies: [homebrew]

environments:
  macos-home: *macos
  macos-work: *macos
