---
name: fontconfig
version: 0.1.0
homepage: 
description: 

_macos: &macos
  install: brew install fontconfig
  check: command -v fc-list
  dependencies: [homebrew]

environments:
  macos-home: *macos
  macos-work: *macos
